export const AUTH_GET_REQUEST_TOKEN = 'user/AUTH_GET_REQUEST_TOKEN'
export const AUTH_GET_REQUEST_TOKEN_SUCCESS = 'user/AUTH_GET_REQUEST_TOKEN_SUCCESS'
export const AUTH_GET_REQUEST_TOKEN_FAIL = 'user/AUTH_GET_REQUEST_TOKEN_FAIL'

export const AUTH_GET_ACCESS_TOKEN = 'user/AUTH_GET_ACCESS_TOKEN'
export const AUTH_GET_ACCESS_TOKEN_SUCCESS = 'user/AUTH_GET_ACCESS_TOKEN_SUCCESS'
export const AUTH_GET_ACCESS_TOKEN_FAIL = 'user/AUTH_GET_ACCESS_TOKEN_FAIL'

export const AUTH_GET_REFRESH_TOKEN = 'user/AUTH_GET_REQUEST_TOKEN'

export const UNAUTHORIZE_REQUEST = 'user/UNAUTHORIZE_REQUEST'

export const AUTH_FAIL_REQUEST = 'user/AUTH_FAIL_REQUEST'
export const AUTH_SUCCESS_REQUEST = 'user/AUTH_SUCCESS_REQUEST'