export const AUTH_GET_REQUEST_TOKEN = 'auth/AUTH_GET_REQUEST_TOKEN'
export const AUTH_GET_REQUEST_TOKEN_SUCCESS = 'auth/AUTH_GET_REQUEST_TOKEN_SUCCESS'
export const AUTH_GET_REQUEST_TOKEN_FAIL = 'auth/AUTH_GET_REQUEST_TOKEN_FAIL'

export const AUTH_GET_ACCESS_TOKEN = 'auth/AUTH_GET_ACCESS_TOKEN'
export const AUTH_GET_ACCESS_TOKEN_SUCCESS = 'auth/AUTH_GET_ACCESS_TOKEN_SUCCESS'
export const AUTH_GET_ACCESS_TOKEN_FAIL = 'auth/AUTH_GET_ACCESS_TOKEN_FAIL'

export const AUTH_CHECK_AUTH = 'auth/AUTH_CHECK_AUTH'
export const AUTH_CHECK_AUTH_SUCCESS = 'auth/AUTH_CHECK_AUTH_SUCCESS'
export const AUTH_CHECK_AUTH_FAIL = 'auth/AUTH_CHECK_AUTH_FAIL'

export const UNAUTHORIZE_REQUEST = 'user/UNAUTHORIZE_REQUEST'